# Generated by Django 4.1.7 on 2023-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=1000)),
                ("image", models.ImageField(upload_to="imgs/")),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Certificaciones",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=1000)),
                ("image", models.ImageField(upload_to="imgs/")),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Projects",
            },
        ),
    ]
